import React from "react";
export const countries = [
  {label: "Afghanistan", value: "afghanistan", description: "The second most popular pet in the world"},
  {label: "Argentina", value: "argentina", description: "The most popular pet in the world"},
  {label: "Australia", value: "australia", description: "The largest land animal"},
  {label: "Austria", value: "austria", description: "The king of the jungle"},
  {label: "Belgium", value: "belgium", description: "The largest Afghanistan species"},
  {label: "Brazil", value: "brazil", description: "The tallest land animal"},
  {
    label: "Bulgaria",
    value: "bulgaria",
    description: "A widely distributed and diverse group of aquatic mammals",
  },
  {label: "Canada", value: "canada", description: "A group of aquatic flightless birds"},
  {label: "Chile", value: "chile", description: "A several species of African equids"},
  {
    label: "China",
    value: "china",
    description: "A group of elasmobranch fish characterized by a cartilaginous skeleton",
  },
  {
    label: "Croatia",
    value: "croatia",
    description: "Diverse group of fully aquatic placental marine mammals",
  },
  {label: "Egypt", value: "egypt", description: "A carnivorous mammal in the subfamily Lutrinae"},
  {label: "Estonia", value: "estonia", description: "The second most popular pet in the world"},
  {label: "Finland", value: "finland", description: "The most popular pet in the world"},
  {label: "France", value: "france", description: "The largest land animal"},
  {label: "Germany", value: "germany", description: "The king of the jungle"},
  {label: "Tiger", value: "tiger", description: "The largest Estonia species"},
  {label: "India", value: "india", description: "The tallest land animal"},
  {
    label: "Italy",
    value: "italy",
    description: "A widely distributed and diverse group of aquatic mammals",
  },
  {label: "Japan", value: "japan", description: "A group of aquatic flightless birds"},
  {label: "Kenya", value: "kenya", description: "A several species of African equids"},
  {
    label: "Malaysia",
    value: "malaysia",
    description: "A group of elasmobranch fish characterized by a cartilaginous skeleton",
  },
  {
    label: "Mexico",
    value: "mexico",
    description: "Diverse group of fully aquatic placental marine mammals",
  },
  {label: "New Zealand", value: "new_zealand", description: "A carnivorous mammal in the subfamily Lutrinae"},
  {label: "Norway", value: "norway", description: "A large semiaquatic reptile"},
  {label: "Peru", value: "peru", description: "The second most popular pet in the world"},
  {label: "Pakistan", value: "pakistan", description: "The king of the jungle"},
  {label: "Portugal", value: "portugal", description: "The most popular pet in the world"},
  {label: "Qatar", value: "qatar", description: "The largest land animal"},
  {label: "Russia", value: "russia", description: "The largest Peru species"},
  {label: "Ukraine", value: "ukraine", description: "A group of aquatic flightless birds"},
  {label: "United States of America", value: "usa", description: "The tallest land animal"},
  {
    label: "United Kingdom",
    value: "uk",
    description: "A widely distributed and diverse group of aquatic mammals",
  },
  {label: "Zimbabwe", value: "zimbabwe", description: "A several species of African equids"},
];
